#!/bin/bash
#SBATCH -J cuda_install           # Job name
#SBATCH -o cuda_install.o%j       # Name of stdout output file
#SBATCH -e cuda_install.o%j       # Name of stderr error file
#SBATCH -p gpu-a100-small
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 0:30:00
#SBATCH --mail-type=end
#SBATCH -A A-ccsc
#SBATCH --mail-user=eijkhout@tacc.utexas.edu

source ${HOME}/Software/env_ls6_intel24.sh
module load cuda/12
make gpu

source ${HOME}/Software/env_ls6_gcc13.sh
module load cuda/12
make gpu

