################################################################
####
#### Makefile for DEMANGLER installation
####
################################################################

PACKAGE = DEMANGLER
PACKAGEVERSION = git
MODE = seq

include ${MAKEINCLUDES}/Make.info

# PKGCONFIG = lib64/pkgconfig
# include ${MAKEINCLUDES}/Make.cmake
# include ${MAKEINCLUDES}/Make.cbuild

GITREPO = https://github.com/FearlessTobi/GccDemangler.git
include ${MAKEINCLUDES}/Make.git

