#!/bin/bash

#SBATCH -J install           # Job name
#SBATCH -o install.o%j       # Name of stdout output file
#SBATCH -e install.o%j       # Name of stderr error file
#SBATCH -p small      # Queue (partition) name
#SBATCH -N 1               # Total # of nodes 
#SBATCH -n 1              # Total # of mpi tasks
#SBATCH -t 06:0:00        # Run time (hh:mm:ss)
#SBATCH -A A-ccsc       # Allocation name (req'd if you have more than 1)

make configure build JCOUNT=24
