################################################################
####
#### Makefile for pcre
####
#### https://www.pcre.org/
####
################################################################

PACKAGE = pcre2
PACKAGEROOT = ${STOCKYARD}
PACKAGEVERSION = git 
MODE = seq

include ${MAKEINCLUDES}/Make.info

include ${MAKEINCLUDES}/Make.configure
include ${MAKEINCLUDES}/Make.install

GITREPO = https://github.com/PhilipHazel/pcre2.git
include ${MAKEINCLUDES}/Make.git
