################################################################
####
#### Makefile for fmtlib
####
################################################################

PACKAGE = fmtlib
PACKAGEROOT = ${STOCKYARD}
PACKAGEVERSION = 6.1.2
MODE = seq

include ${MAKEINCLUDES}/Make.info

include ${MAKEINCLUDES}/Make.cmake
include ${MAKEINCLUDES}/Make.cbuild

TGZURL = https://github.com/fmtlib/fmt/archive/${PACKAGEVERSION}.tar.gz
include ${MAKEINCLUDES}/Make.download
