################################################################
####
#### Makefile for infrastructure testing
####
################################################################

PROGRAMS = clangversion
MODE = seq

include ${MAKEINCLUDES}/Make.info

clean ::
	@rm -f ${PROGRAMS}
