################################################################
####
#### Makefile for gsl
####
################################################################

PACKAGE = gsl
PACKAGEVERSION = 4.0.0
URL = https://github.com/microsoft/GSL
MODE = seq

include ${MAKEINCLUDES}/Make.info

include ${MAKEINCLUDES}/Make.cmake
include ${MAKEINCLUDES}/Make.cbuild


TGZURL = https://github.com/microsoft/GSL/archive/refs/tags/v${PACKAGEVERSION}.tar.gz
include ${MAKEINCLUDES}/Make.download
